/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DtButtonColor, DtButtonVariant } from "./components/dt-button/dt-button";
export namespace Components {
    interface DtButton {
        /**
          * The button color
         */
        "color": DtButtonColor;
        /**
          * Disabled state for the button
         */
        "disabled": boolean;
        /**
          * The button variant
         */
        "variant": DtButtonVariant;
    }
}
declare global {
    interface HTMLDtButtonElement extends Components.DtButton, HTMLStencilElement {
    }
    var HTMLDtButtonElement: {
        prototype: HTMLDtButtonElement;
        new (): HTMLDtButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dt-button": HTMLDtButtonElement;
    }
}
declare namespace LocalJSX {
    interface DtButton {
        /**
          * The button color
         */
        "color"?: DtButtonColor;
        /**
          * Disabled state for the button
         */
        "disabled"?: boolean;
        /**
          * The button variant
         */
        "variant"?: DtButtonVariant;
    }
    interface IntrinsicElements {
        "dt-button": DtButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dt-button": LocalJSX.DtButton & JSXBase.HTMLAttributes<HTMLDtButtonElement>;
        }
    }
}
